services:
  fastapi_app_1:
    build: .
    container_name: fastapi_app_1
    restart: always
    network_mode: "host"
    command: uvicorn app.main:app --host 127.0.0.1 --port 8001
    env_file:
      - .env

  fastapi_app_2:
    build: .
    container_name: fastapi_app_2
    restart: always
    network_mode: "host"
    command: uvicorn app.main:app --host 127.0.0.1 --port 8002
    env_file:
      - .env