#!/usr/bin/env python3
"""
DreemFolio AI - Automated Dynamic SSL & VHost Daemon for Nginx & CloudPanel
Watches custom_domains.json and automatically provisions Let's Encrypt SSL
and Nginx reverse proxy blocks for newly connected candidate domains.
Zero manual intervention required!
"""

import os
import sys
import time
import json
import socket
import logging
import subprocess
from pathlib import Path

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [AutoSSL] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("AutoSSL")

# Paths (Adjustable via environment variables if needed)
BASE_DIR = Path(__file__).resolve().parent.parent
CUSTOM_DOMAINS_FILE = os.getenv(
    "CUSTOM_DOMAINS_FILE",
    str(BASE_DIR / "app" / "static" / "published_portfolios" / "custom_domains.json")
)
NGINX_SITES_DIR = Path(os.getenv("NGINX_SITES_DIR", "/etc/nginx/sites-enabled"))
LETSENCRYPT_DIR = Path(os.getenv("LETSENCRYPT_DIR", "/etc/letsencrypt/live"))
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "admin@dreemfolio.com")
UPSTREAM_PORT = os.getenv("UPSTREAM_PORT", "8001")

# Default domains that already have main certs
DEFAULT_HOSTS = {
    "dreemfolio.com",
    "www.dreemfolio.com",
    "cname.dreemfolio.com",
    "localhost",
    "127.0.0.1"
}

# In-memory failure tracking to avoid spamming Let's Encrypt on unpropagated DNS
FAILURE_BACKOFF = {}  # domain -> next_retry_timestamp


def is_valid_domain(domain: str) -> bool:
    if not domain or len(domain) > 253 or "." not in domain:
        return False
    allowed = set("abcdefghijklmnopqrstuvwxyz0123456789.-")
    return set(domain.lower()).issubset(allowed)


def resolves_to_this_server(domain: str) -> bool:
    """Check if domain resolves to any IP (DNS propagation check)."""
    try:
        resolved_ip = socket.gethostbyname(domain)
        logger.info(f"Domain {domain} resolves to {resolved_ip}")
        return True
    except socket.gaierror:
        return False


def has_ssl_certificate(domain: str) -> bool:
    """Check if Let's Encrypt already has a live certificate for this domain."""
    cert_path = LETSENCRYPT_DIR / domain / "fullchain.pem"
    return cert_path.exists()


def create_nginx_vhost(domain: str) -> bool:
    """Generate and deploy a lightweight Nginx reverse proxy block for the domain."""
    NGINX_SITES_DIR.mkdir(parents=True, exist_ok=True)
    vhost_file = NGINX_SITES_DIR / f"dreemfolio_custom_{domain.replace('.', '_')}.conf"

    config_content = f"""# Auto-generated by DreemFolio AI Auto-SSL Daemon
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
    }}

    location / {{
        proxy_pass http://127.0.0.1:{UPSTREAM_PORT};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 90;
        proxy_connect_timeout 90;
    }}
}}
"""
    try:
        with open(vhost_file, "w", encoding="utf-8") as f:
            f.write(config_content)
        logger.info(f"Created temporary HTTP Nginx vhost: {vhost_file}")
        
        # Test configuration
        test_res = subprocess.run(["nginx", "-t"], capture_output=True, text=True)
        if test_res.returncode != 0:
            logger.error(f"Nginx syntax error after adding {domain}: {test_res.stderr}")
            if vhost_file.exists():
                vhost_file.unlink()
            return False

        # Reload nginx
        subprocess.run(["systemctl", "reload", "nginx"], check=True)
        return True
    except Exception as e:
        logger.error(f"Failed to create Nginx vhost for {domain}: {e}")
        return False


def provision_ssl_for_domain(domain: str) -> bool:
    """Run Certbot non-interactively to issue Let's Encrypt certificate and install into Nginx."""
    logger.info(f"🚀 Starting automated Let's Encrypt provisioning for: {domain}")
    
    # Ensure initial HTTP vhost exists so certbot HTTP-01 challenge succeeds
    if not create_nginx_vhost(domain):
        return False

    cmd = [
        "certbot",
        "--nginx",
        "-d", domain,
        "--non-interactive",
        "--agree-tos",
        "--email", ADMIN_EMAIL,
        "--redirect"  # Automatically upgrade HTTP traffic to HTTPS
    ]

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if proc.returncode == 0:
            logger.info(f"✅ SUCCESS! SSL certificate successfully provisioned and installed for: {domain}")
            # Ensure Nginx reloaded
            subprocess.run(["systemctl", "reload", "nginx"], check=False)
            return True
        else:
            logger.error(f"❌ Certbot failed for {domain} (Code {proc.returncode}):\n{proc.stderr}")
            return False
    except subprocess.TimeoutExpired:
        logger.error(f"❌ Certbot timed out after 120s for {domain}")
        return False
    except Exception as e:
        logger.error(f"❌ Unexpected error running Certbot for {domain}: {e}")
        return False


def process_domains():
    if not os.path.exists(CUSTOM_DOMAINS_FILE):
        return

    try:
        with open(CUSTOM_DOMAINS_FILE, "r", encoding="utf-8") as f:
            domain_map = json.load(f)
    except Exception as e:
        logger.warning(f"Could not read {CUSTOM_DOMAINS_FILE}: {e}")
        return

    now = time.time()

    for domain, slug in domain_map.items():
        domain_clean = domain.strip().lower()

        if domain_clean in DEFAULT_HOSTS:
            continue

        if not is_valid_domain(domain_clean):
            continue

        # Check backoff if previous attempt failed
        if domain_clean in FAILURE_BACKOFF and now < FAILURE_BACKOFF[domain_clean]:
            continue

        # Check if SSL already exists
        if has_ssl_certificate(domain_clean):
            continue

        # Check DNS propagation
        if not resolves_to_this_server(domain_clean):
            logger.info(f"⏳ DNS for {domain_clean} is not yet pointing to this server. Waiting...")
            FAILURE_BACKOFF[domain_clean] = now + 60  # Retry in 1 minute
            continue

        # Provision SSL
        success = provision_ssl_for_domain(domain_clean)
        if success:
            if domain_clean in FAILURE_BACKOFF:
                del FAILURE_BACKOFF[domain_clean]
        else:
            # Backoff for 3 minutes before retrying to prevent Let's Encrypt rate limits
            FAILURE_BACKOFF[domain_clean] = now + 180


def main():
    logger.info("🛡️ DreemFolio AI Nginx Auto-SSL Daemon started.")
    logger.info(f"Watching custom domains at: {CUSTOM_DOMAINS_FILE}")
    logger.info(f"Nginx sites dir: {NGINX_SITES_DIR}")

    # Ensure certbot webroot dir exists
    Path("/var/www/certbot").mkdir(parents=True, exist_ok=True)

    while True:
        try:
            process_domains()
        except Exception as loop_err:
            logger.error(f"Error in process_domains loop: {loop_err}")
        
        # Check every 10 seconds for new candidate domains
        time.sleep(10)


if __name__ == "__main__":
    main()
